### ISSUE TITLE
Patch for /fabricate.py

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SimonAlfie/fabricate#53]
```
Fix for options not really saved if parse_options called earlier by user script
```

Original issue reported on code.google.com by `mehultik...@gmail.com` on 5 Nov 2013 at 9:31

Attachments:
- [fabricate.py.patch](https://storage.googleapis.com/google-code-attachments/fabricate/issue-53/comment-0/fabricate.py.patch)

**Comment by chriscz** [comment]
Was fixed by #78
