### ISSUE TITLE
Complete Google Code migration

### ISSUE THREAD

**Issue by johndrinkwater** [SimonAlfie/fabricate#68]
There are some missing elements from the move to GitHub, like the wiki, which may be removed by Jan 2016.

**Comment by SimonAlfie** [comment]
I will take a look at migrating them ASAP.

**Comment by SimonAlfie** [comment]
The wiki has now been moved. I think that is all that need to be done. Let
me know if you think there is anything else missing

**Comment by johndrinkwater** [comment]
Looking good, few remaining tweaks I’ve seen:

Project tagline could be updated to ‘The better build tool. Finds dependencies automatically for any language.’

Some of wiki links point to https://raw.githubusercontent.com/wiki/SimonAlfie/fabricate/HowItWorks.md rather than their rendered versions https://github.com/SimonAlfie/fabricate/wiki/HowItWorks

**Comment by SimonAlfie** [comment]
I will sort that out. I used a conversion tool which I though converted all
the links. I only checked the first link, which by luck worked. Slap dash I
know! :)

**Comment by SimonAlfie** [comment]
I think its mostly sorted now. A few of the external links are broken due
to 'Web Rot' but not gone through them all.

**Comment by chriscz** [comment]
This looks pretty much solved to me. Closing for now
