### ISSUE TITLE
name 'main' is not defined (windows, python 2.7.3)

### ISSUE THREAD

**Issue by blakehawkins** [SimonAlfie/fabricate#72]
Hello,

While trying to run my first toy fabricate script, I get the following error:

```
$ python fabricate.py clean
Traceback (most recent call last):
  File "fabricate.py", line 2, in <module>
    from fabricate import *
  File "C:\Users\Blake\workspace\z\fabricate.py", line 15, in <module>
    main()
NameError: name 'main' is not defined
```

And here is my fabricate.py in full:

```
from fabricate import *

def clean():
    run('echo', '"hello world"')
    run('rm', '-rf', 'z.txt')

def build():
    run('./init.sh')

main()
```

**Comment by chriscz** [comment]
Are you still experiencing this issue?
Also, I'm not sure is `.sh` and `rm` are available of vanilla Windows.

**Comment by chriscz** [comment]
It seems that python is finding the fact that you import `fabricate` from `frabicate.py` confusing. Instead, rename your file to `build.py` and try again.

Also make sure you have the latest version of fabricate installed.
