### ISSUE TITLE
Turn on Travis CI testing on for this repo

### ISSUE THREAD

**Issue by cclauss** [SimonAlfie/fabricate#81]
This will then be free and will run automatically on each pull request. See: https://www.smartfile.com/blog/testing-python-with-travis-ci/

**Comment by chriscz** [comment]
@SimonAlfie could you please activate this repository using your account, as only repository owners may enable it.

**Comment by SimonAlfie** [comment]
OK. How do you enable it?

**Comment by cclauss** [comment]
Please read thru the URL above.

**Comment by SimonAlfie** [comment]
It is done, and is syncing from git hub.

I only asked because the "Sign Up" option through that URL does not allow
you to sign up for Travis CI. Once I found the Travis CI sign up it was
trivial.

**Comment by cclauss** [comment]
This is now successfully turned on and running properly so I will close this issue.

However, there is a **_new issue_**, the tests are failing.  :-(
https://travis-ci.org/SimonAlfie/fabricate/builds/228487606
