### ISSUE TITLE
Update fabricate on pypi

### ISSUE THREAD

**Issue by kroesche** [SimonAlfie/fabricate#82]
The version of fabricate on pypi is 1.26 from 2014 and is not compatible with python 3.  Because of this:

```
      File "/private/var/folders/jk/932r_8px3pqbfk06h518tsq4001ktt/T/pip-build-vxzv3cfh/fabricate/fabricate.py", line 183
        except OSError, e:
                      ^
    SyntaxError: invalid syntax
```

**Comment by chriscz** [comment]
Ok I'll be uploading the updated version this week.
I was still waiting for a response from the other maintainers regarding our next release.

**Comment by kroesche** [comment]
Thank you for your work on this module.  I have started using it in a project at work, but we mostly use python 3 and it is a lot easier to tell people to pip install rather than build separately.  This is why I made the request.

**Comment by chriscz** [comment]
[It has been done](https://pypi.python.org/pypi/fabricate/). Please report any issue you experience ;)
